pipelines:
  branches: # Branches-specific piplines defination
    master:
    - step:
        name: Build and test the app
        image: node:latest
        script:
          - npm install
          - npm run test
          - npm run build